### ISSUE TITLE
Artificial slow start

### ISSUE THREAD

**Issue by Tollefsen** [Tollefsen/neurosky-lindenmayer#12]
Sometimes the user is already focused when we start generating. It feels weird to start at 100km/h.
We should let the speed "accelerate" the first two seconds, so it feels more natural.

**Comment by daniesso** [comment]
[Implementert her](https://github.com/Tollefsen/neurosky-lindenmayer/commit/24eca7ec76f42f4e449732f637d96ea69d0656ac)
